//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public string id { get; set; }
        public string partyId { get; set; }
        public string provider { get; set; }
        public string token { get; set; }
        public string jsonUserInfo { get; set; }
        public Nullable<bool> C__deleted { get; set; }
        public string userName { get; set; }
    }
}
