//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bvcMobSvc_dbEntities : DbContext
    {
        public bvcMobSvc_dbEntities()
            : base("name=bvcMobSvc_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<foodStorage> foodStorage { get; set; }
        public virtual DbSet<party> party { get; set; }
        public virtual DbSet<userInfoGoogle> userInfoGoogle { get; set; }
    }
}
